plugins {
    id 'com.android.application'
}

android {
    namespace 'com.hellonetra.ocr'
    compileSdk 35

    defaultConfig {
        applicationId 'com.hellonetra.ocr'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += [
                "META-INF/INDEX.LIST",
                "META-INF/DEPENDENCIES",
                "META-INF/LICENSE*",
                "META-INF/NOTICE*"
            ]
        }
    }
}

dependencies {
    implementation 'com.microsoft.onnxruntime:onnxruntime-android:1.21.1'
    implementation 'com.quickbirdstudios:opencv:4.5.3.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0'
}